### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by NickGrantONS**
# Motivation and Context
I was on holiday and a PR got raised and I didn't get a chance to review & comment. Now I'm fixing the stuff which I'd have commented on.

# What has changed
Fixed stuff that in my opinion, I would have asked to be done as part of previous PR.

# How to test?
Run the tests.

# Links
Trello: https://trello.com/c/RK7OnzRY

### CODE REVIEW

**Comment by NickGrantONS** [comment]
[Extra "late" PR review of case event handling](https://trello.com/c/RK7OnzRY/2380-extra-late-pr-review-of-case-event-handling)

**Review by ryangrundy7 — COMMENTED** [review]
Seeing this test failure
```
[ERROR] Failures:
[ERROR]   SurveyLaunchedReceiverIT.testSurveyLaunchLogsEventSetsFlagAndEmitsCorrectCaseUpdatedEvent:115
Expecting:
 <true>
to be equal to:
 <false>
but was not.
```

**Comment by AdamHawtin** [comment]
@ryangrundy7 I think that failure was actually caused by my PR #4, but it's the test that is faulty. It is expecting a UAC to be inactive when the only event that has happened since creation is a survey launch.

**Review by AdamHawtin — APPROVED** [review]
👍 All the changes here

**Review by hbrace — APPROVED** [review]

**Pull request merged**
